SET SERVEROUTPUT ON;
-- 1
CREATE TABLE STUDENTS_LOG (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    GROUP_ID NUMBER
);

-- 2
BEGIN
    FOR i IN 1..10 LOOP
        INSERT INTO STUDENTS_LOG (ID, NAME, GROUP_ID) 
        VALUES (i, 'Student_' || i, MOD(i, 3) + 1);
    END LOOP;
    COMMIT;
END;
/

-- 3-4
CREATE OR REPLACE TRIGGER TR_BEFORE_STMT_STUDENTS
BEFORE INSERT OR DELETE OR UPDATE ON STUDENTS_LOG
BEGIN
    DBMS_OUTPUT.PUT_LINE('TR_BEFORE_STMT_STUDENTS: Начало выполнения оператора.');
    IF INSERTING THEN
        DBMS_OUTPUT.PUT_LINE('Событие: INSERT');
    ELSIF UPDATING THEN
        DBMS_OUTPUT.PUT_LINE('Событие: UPDATE');
    ELSIF DELETING THEN
        DBMS_OUTPUT.PUT_LINE('Событие: DELETE');
    END IF;
END;
/

-- 5-6
CREATE OR REPLACE TRIGGER TR_BEFORE_ROW_STUDENTS
BEFORE INSERT OR DELETE OR UPDATE ON STUDENTS_LOG
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('TR_BEFORE_ROW_STUDENTS: Обработка строки.');
END;
/

-- 7
CREATE OR REPLACE TRIGGER TR_AFTER_STMT_STUDENTS
AFTER INSERT OR DELETE OR UPDATE ON STUDENTS_LOG
BEGIN
    DBMS_OUTPUT.PUT_LINE('TR_AFTER_STMT_STUDENTS: Завершение выполнения оператора.');
END;
/

-- 8
CREATE OR REPLACE TRIGGER TR_AFTER_ROW_STUDENTS
AFTER INSERT OR DELETE OR UPDATE ON STUDENTS_LOG
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('TR_AFTER_ROW_STUDENTS: Строка обработана.');
END;
/

-- 9
INSERT INTO STUDENTS_LOG VALUES (11, 'Test', 1);

CREATE TABLE AUDIT_LOG (
    OperationDate DATE,
    OperationType VARCHAR2(20),
    TriggerName VARCHAR2(50),
    Data VARCHAR2(4000)
);

-- 10
CREATE OR REPLACE TRIGGER TR_BEFORE_STMT_STUDENTS
BEFORE INSERT OR DELETE OR UPDATE ON STUDENTS_LOG
DECLARE
    v_type VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_type := 'INSERT';
    ELSIF UPDATING THEN v_type := 'UPDATE';
    ELSIF DELETING THEN v_type := 'DELETE';
    END IF;
    
    DBMS_OUTPUT.PUT_LINE('TR_BEFORE_STMT_STUDENTS executed');
    INSERT INTO AUDIT_LOG (OperationDate, OperationType, TriggerName, Data)
    VALUES (SYSDATE, v_type, 'TR_BEFORE_STMT_STUDENTS', 'None (Statement Level)');
END;
/
CREATE OR REPLACE TRIGGER TR_BEFORE_ROW_STUDENTS
BEFORE INSERT OR DELETE OR UPDATE ON STUDENTS_LOG
FOR EACH ROW
DECLARE
    v_type VARCHAR2(20);
    v_data VARCHAR2(4000);
BEGIN
    IF INSERTING THEN 
        v_type := 'INSERT';
        v_data := 'New ID: ' || :NEW.ID || ', Name: ' || :NEW.NAME;
    ELSIF UPDATING THEN 
        v_type := 'UPDATE';
        v_data := 'Old ID: ' || :OLD.ID || ' -> New ID: ' || :NEW.ID;
    ELSIF DELETING THEN 
        v_type := 'DELETE';
        v_data := 'Old ID: ' || :OLD.ID;
    END IF;

    DBMS_OUTPUT.PUT_LINE('TR_BEFORE_ROW_STUDENTS executed');
    INSERT INTO AUDIT_LOG (OperationDate, OperationType, TriggerName, Data)
    VALUES (SYSDATE, v_type, 'TR_BEFORE_ROW_STUDENTS', v_data);
END;
/
CREATE OR REPLACE TRIGGER TR_AFTER_STMT_STUDENTS
AFTER INSERT OR DELETE OR UPDATE ON STUDENTS_LOG
DECLARE
    v_type VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_type := 'INSERT';
    ELSIF UPDATING THEN v_type := 'UPDATE';
    ELSIF DELETING THEN v_type := 'DELETE';
    END IF;

    DBMS_OUTPUT.PUT_LINE('TR_AFTER_STMT_STUDENTS executed');
    INSERT INTO AUDIT_LOG (OperationDate, OperationType, TriggerName, Data)
    VALUES (SYSDATE, v_type, 'TR_AFTER_STMT_STUDENTS', 'None (Statement Level)');
END;
/
CREATE OR REPLACE TRIGGER TR_AFTER_ROW_STUDENTS
AFTER INSERT OR DELETE OR UPDATE ON STUDENTS_LOG
FOR EACH ROW
DECLARE
    v_type VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_type := 'INSERT';
    ELSIF UPDATING THEN v_type := 'UPDATE';
    ELSIF DELETING THEN v_type := 'DELETE';
    END IF;

    DBMS_OUTPUT.PUT_LINE('TR_AFTER_ROW_STUDENTS executed');
    INSERT INTO AUDIT_LOG (OperationDate, OperationType, TriggerName, Data)
    VALUES (SYSDATE, v_type, 'TR_AFTER_ROW_STUDENTS', 'Finished row processing');
END;
/

-- 11
INSERT INTO STUDENTS_LOG (ID, NAME, GROUP_ID) VALUES (1, 'Duplicated', 5);
SELECT * FROM AUDIT_LOG ORDER BY OperationDate DESC;

-- 12
DROP TABLE STUDENTS_LOG;

CREATE TABLE STUDENTS_LOG (ID NUMBER PRIMARY KEY, NAME VARCHAR2(50), GROUP_ID NUMBER);

CREATE OR REPLACE TRIGGER TR_PREVENT_DROP
BEFORE DROP ON SCHEMA
BEGIN
    IF ORA_DICT_OBJ_NAME = 'STUDENTS_LOG' THEN
        RAISE_APPLICATION_ERROR(-20001, 'Удаление таблицы STUDENTS_LOG запрещено!');
    END IF;
END;
/

-- 13
DROP TABLE AUDIT_LOG;
SELECT TRIGGER_NAME, STATUS FROM USER_TRIGGERS WHERE TABLE_NAME = 'STUDENTS_LOG';

-- 14
CREATE OR REPLACE VIEW V_STUDENTS AS
SELECT * FROM STUDENTS_LOG;
CREATE OR REPLACE TRIGGER TR_INSTEAD_OF_INSERT
INSTEAD OF INSERT ON V_STUDENTS
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('Сработал триггер INSTEAD OF. Вставляем в таблицу...');
    INSERT INTO STUDENTS_LOG (ID, NAME, GROUP_ID)
    VALUES (:NEW.ID, :NEW.NAME, :NEW.GROUP_ID);
END;
/

-- 15
INSERT INTO V_STUDENTS (ID, NAME, GROUP_ID) VALUES (100, 'View_User', 2);